let db, viewer; const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const openDB=()=>new Promise((res,rej)=>{const r=indexedDB.open('Vietnam360DB',1);r.onupgradeneeded=()=>r.result.createObjectStore('places',{keyPath:'id'});r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)});
const allPlaces=()=>new Promise(res=>{const r=db.transaction('places').objectStore('places').getAll();r.onsuccess=()=>res(r.result)});
const savePlace=p=>new Promise(res=>{const r=db.transaction('places','readwrite').objectStore('places').put(p);r.onsuccess=res});
const deletePlace=id=>new Promise(res=>{const r=db.transaction('places','readwrite').objectStore('places').delete(id);r.onsuccess=res});
function route(){const id=(location.hash||'#home').slice(1);$$('.page').forEach(x=>x.classList.remove('active'));($('#'+id)||$('#home')).classList.add('active');$('#nav').classList.remove('open'); if(['gallery','tour','manage','home'].includes(id)) renderAll()}
window.addEventListener('hashchange',route);$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');
const blobURL=b=>URL.createObjectURL(b);
async function renderAll(){if(!db)return;const ps=await allPlaces();$('#statPlaces').textContent=ps.length;$('#statPhotos').textContent=ps.reduce((n,p)=>n+p.images.length,0);$('#placeList').innerHTML=ps.length?ps.map(p=>`<div class="place-item" data-id="${p.id}"><b>${esc(p.name)}</b><br><small>${p.images.length} panorama</small></div>`).join(''):'<p>Chưa có địa điểm.</p>'; $$('#placeList .place-item').forEach(el=>el.onclick=()=>openTour(el.dataset.id));$('#galleryGrid').innerHTML=ps.flatMap(p=>p.images.map((im,i)=>`<article class="card"><img src="${blobURL(im.blob)}"><div class="card-body"><b>${esc(p.name)}</b><p>Panorama ${i+1}</p></div></article>`)).join('')||'<p>Kho ảnh đang trống.</p>';$('#manageList').innerHTML=ps.map(p=>`<div class="manage-row"><span><b>${esc(p.name)}</b> · ${p.images.length} ảnh</span><button class="danger" data-del="${p.id}">Xóa</button></div>`).join('')||'<p>Chưa có dữ liệu.</p>';$$('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Xóa địa điểm này?')){await deletePlace(b.dataset.del);renderAll()}})}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
$('#panoFiles').onchange=e=>{$('#preview').innerHTML=[...e.target.files].map(f=>`<img src="${URL.createObjectURL(f)}">`).join('')};
$('#placeForm').onsubmit=async e=>{e.preventDefault();const files=[...$('#panoFiles').files];const p={id:crypto.randomUUID(),name:$('#placeName').value.trim(),desc:$('#placeDesc').value.trim(),createdAt:Date.now(),images:files.map(f=>({name:f.name,type:f.type,blob:f}))};await savePlace(p);e.target.reset();$('#preview').innerHTML='';$('#saveStatus').textContent='Đã lưu địa điểm và panorama trên trình duyệt.';renderAll()};
async function openTour(id){const p=(await allPlaces()).find(x=>x.id===id);if(!p||!p.images.length)return;const scenes={};p.images.forEach((im,i)=>scenes['s'+i]={title:p.name+' · '+(i+1),type:'equirectangular',panorama:blobURL(im.blob),autoLoad:true});if(viewer)try{viewer.destroy()}catch{};viewer=pannellum.viewer('viewer',{default:{firstScene:'s0',sceneFadeDuration:700},scenes});$('#sceneBar').innerHTML=p.images.map((_,i)=>`<button data-scene="s${i}">Ảnh ${i+1}</button>`).join('');$$('[data-scene]').forEach(b=>b.onclick=()=>viewer.loadScene(b.dataset.scene))}
$('#placeSearch').oninput=e=>{const q=e.target.value.toLowerCase();$$('.place-item').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'block':'none')};
$('#chatForm').onsubmit=async e=>{e.preventDefault();const inp=$('#chatInput'),q=inp.value.trim();if(!q)return;addMsg(q,'user');inp.value='';const wait=addMsg('Đang trả lời...','bot');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});const d=await r.json();wait.textContent=d.text||d.error||'Không nhận được phản hồi.'}catch{wait.textContent='ChatAI cần deploy trên Vercel và cấu hình GEMINI_API_KEY. GitHub Pages không chạy được serverless API này.'}}
function addMsg(t,c){const d=document.createElement('div');d.className='msg '+c;d.textContent=t;$('#messages').append(d);d.scrollIntoView();return d}
$('#supportForm').onsubmit=e=>{e.preventDefault();const subject=encodeURIComponent($('#supportSubject').value),body=encodeURIComponent(`Họ tên: ${$('#supportName').value}\nEmail: ${$('#supportEmail').value}\n\n${$('#supportMessage').value}`);location.href=`mailto:?subject=${subject}&body=${body}`};
openDB().then(()=>{route();renderAll()});
